#!/bin/sh
unset IFS
set -euf

cargo install --force unmake@0.0.3

go install github.com/mrtazz/checkmake/...@0.2.1
go mod tidy

pip3 install --upgrade pip setuptools
pip3 install -r requirements-dev.txt
